name: Test

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  test:
    runs-on: [ubuntu-latest, windows-latest, macos-latest]
    strategy:
      matrix:
        nvim-versions: ['stable', 'nightly']
    name: Plenary Tests
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
          version: ${{ matrix.nvim-versions }}

      - name: run tests
        run: make test
